# Generated by Django 4.1.3 on 2022-11-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/'),
        ),
    ]
